export const miniWords = [
  {id:'dino',topic:'dinosaurios',word:'DINO',syllables:['DI','NO'],distractor:'MA',emoji:'🦕',phrase:'El dino camina.'},
  {id:'huevo',topic:'dinosaurios',word:'HUEVO',syllables:['HUE','VO'],distractor:'SA',emoji:'🥚',phrase:'El huevo brilla.'},
  {id:'lava',topic:'dinosaurios',word:'LAVA',syllables:['LA','VA'],distractor:'RO',emoji:'🌋',phrase:'La lava está lejos.'},
  {id:'cueva',topic:'dinosaurios',word:'CUEVA',syllables:['CUE','VA'],distractor:'PI',emoji:'🪨',phrase:'Roki entra en la cueva.'},
  {id:'roca',topic:'dinosaurios',word:'ROCA',syllables:['RO','CA'],distractor:'ME',emoji:'🪨',phrase:'Roki mira la roca.'},
  {id:'mapa',topic:'aventuras',word:'MAPA',syllables:['MA','PA'],distractor:'TO',emoji:'🗺️',phrase:'Roki mira el mapa.'},
  {id:'ruta',topic:'aventuras',word:'RUTA',syllables:['RU','TA'],distractor:'MI',emoji:'🧭',phrase:'La ruta es segura.'},
  {id:'puente',topic:'aventuras',word:'PUENTE',syllables:['PUEN','TE'],distractor:'LA',emoji:'🌉',phrase:'Cruzamos el puente.'},
  {id:'cofre',topic:'aventuras',word:'COFRE',syllables:['CO','FRE'],distractor:'NA',emoji:'🧰',phrase:'El cofre tiene pistas.'},
  {id:'isla',topic:'aventuras',word:'ISLA',syllables:['IS','LA'],distractor:'PO',emoji:'🏝️',phrase:'La isla está cerca.'},
  {id:'capa',topic:'heroes',word:'CAPA',syllables:['CA','PA'],distractor:'RI',emoji:'🦸',phrase:'La capa vuela.'},
  {id:'salto',topic:'heroes',word:'SALTO',syllables:['SAL','TO'],distractor:'ME',emoji:'🕸️',phrase:'Hilito da un salto.'},
  {id:'ayuda',topic:'heroes',word:'AYUDA',syllables:['A','YU','DA'],distractor:'FO',emoji:'🤝',phrase:'Ayudar nos hace fuertes.'},
  {id:'escudo',topic:'heroes',word:'ESCUDO',syllables:['ES','CU','DO'],distractor:'MA',emoji:'🛡️',phrase:'El escudo protege.'},
  {id:'equipo',topic:'heroes',word:'EQUIPO',syllables:['E','QUI','PO'],distractor:'SA',emoji:'🫶',phrase:'Somos un equipo.'},
  {id:'rayo',topic:'velocidad',word:'RAYO',syllables:['RA','YO'],distractor:'MI',emoji:'⚡',phrase:'El rayo ilumina.'},
  {id:'meta',topic:'velocidad',word:'META',syllables:['ME','TA'],distractor:'RO',emoji:'🏁',phrase:'Turbo llega a la meta.'},
  {id:'pista',topic:'velocidad',word:'PISTA',syllables:['PIS','TA'],distractor:'LU',emoji:'🛤️',phrase:'La pista tiene curvas.'},
  {id:'paso',topic:'velocidad',word:'PASO',syllables:['PA','SO'],distractor:'NI',emoji:'👟',phrase:'Vamos paso a paso.'},
  {id:'freno',topic:'velocidad',word:'FRENO',syllables:['FRE','NO'],distractor:'CA',emoji:'🛑',phrase:'Turbo usa el freno.'}
];

export const miniStories = [
  {id:'roki-huevo-luminoso',topic:'dinosaurios',title:'Roki y el huevo luminoso',emoji:'🥚',keyword:'HUEVO',syllables:['HUE','VO'],pages:['Roki camina junto al río. Sus pasos hacen: toc, toc.','Detrás de una roca encuentra un huevo azul y brillante.','Roki no lo toca. Primero llama a Tinkie para pedir ayuda.','Tinkie mira el huevo. Dentro se escucha un suave: pío, pío.','Los dos esperan con calma. Una cría de dinosaurio asoma la cabeza.'],question:{text:'¿Qué encontró Roki detrás de la roca?',options:['Un huevo azul','Una pelota roja'],correct:0}},
  {id:'turbo-mapa-colores',topic:'aventuras',title:'Turbo y el mapa de colores',emoji:'🗺️',keyword:'MAPA',syllables:['MA','PA'],pages:['Turbo corre por el bosque, pero se detiene al ver un mapa.','El mapa tiene caminos verdes, amarillos y azules.','Roki propone mirar cada señal antes de escoger una ruta.','Los amigos siguen el camino azul y encuentran un puente tranquilo.','Turbo descubre que observar con calma también es parte de una aventura.'],question:{text:'¿Qué camino escogieron los amigos?',options:['El camino azul','El camino rojo'],correct:0}},
  {id:'hilito-puente-amable',topic:'heroes',title:'Hilito y el puente amable',emoji:'🕸️',keyword:'AYUDA',syllables:['A','YU','DA'],pages:['Hilito ve que una tortuga quiere cruzar un pequeño charco.','Con su red prepara un puente firme y suave.','Roki sostiene una punta mientras Tinkie mira desde arriba.','La tortuga cruza despacio y da las gracias a todo el equipo.','Hilito aprende que ayudar también es una forma de ser héroe.'],question:{text:'¿Para quién construyeron el puente?',options:['Para una tortuga','Para un pez'],correct:0}},
  {id:'turbo-carrera-tranquila',topic:'velocidad',title:'Turbo y la carrera tranquila',emoji:'🏁',keyword:'META',syllables:['ME','TA'],pages:['Turbo prepara sus zapatos para una carrera por el parque.','Al comenzar, corre muy rápido y casi olvida mirar la pista.','Tinkie le recuerda que puede respirar y observar cada curva.','Turbo baja la velocidad, usa el freno y sigue paso a paso.','Llega a la meta contento porque corrió de forma segura.'],question:{text:'¿Qué hizo Turbo antes de seguir?',options:['Respiró y miró la pista','Cerró los ojos'],correct:0}}
];

export const miniSoundLessons={
  d:{letter:'D',model:'dddd, dino',correct:'DINO',choices:['DINO','MAPA','HUEVO']},
  m:{letter:'M',model:'mmmm, mapa',correct:'MAPA',choices:['MAPA','DINO','HUEVO']},
  a:{letter:'A',model:'aaaa, ayuda',correct:'AYUDA',choices:['AYUDA','CAPA','SALTO']},
  r:{letter:'R',model:'rrrr, rayo',correct:'RAYO',choices:['RAYO','META','PISTA']}
};

export const miniTopics=[
  {id:'dinosaurios',emoji:'🦕',title:'Mundo dinosaurio',subtitle:'Huevos, cuevas y volcanes',sound:'d',story:'roki-huevo-luminoso',offline:'Camina como un dinosaurio y di DI · NO.',wordIds:['dino','huevo','lava','cueva','roca']},
  {id:'aventuras',emoji:'🗺️',title:'Mapas y aventuras',subtitle:'Rutas, puentes e islas',sound:'m',story:'turbo-mapa-colores',offline:'Dibuja una ruta sencilla y señala dónde empieza.',wordIds:['mapa','ruta','puente','cofre','isla']},
  {id:'heroes',emoji:'🦸',title:'Héroes que ayudan',subtitle:'Capas, redes y trabajo en equipo',sound:'a',story:'hilito-puente-amable',offline:'Haz una acción amable y di A · YU · DA.',wordIds:['capa','salto','ayuda','escudo','equipo']},
  {id:'velocidad',emoji:'⚡',title:'Velocidad segura',subtitle:'Pistas, metas y autocuidado',sound:'r',story:'turbo-carrera-tranquila',offline:'Corre cinco pasos, frena y respira con calma.',wordIds:['rayo','meta','pista','paso','freno']}
];

const extraWordSets={
  animales:[['gato','GATO',['GA','TO'],'PE','🐈','El gato camina.'],['perro','PERRO',['PE','RRO'],'CA','🐕','El perro mueve la cola.'],['pato','PATO',['PA','TO'],'MI','🦆','El pato nada.'],['rana','RANA',['RA','NA'],'LU','🐸','La rana salta.'],['oso','OSO',['O','SO'],'TE','🐻','El oso descansa.']],
  cuerpo:[['mano','MANO',['MA','NO'],'PI','✋','Esta es mi mano.'],['boca','BOCA',['BO','CA'],'RE','👄','La boca sonríe.'],['nariz','NARIZ',['NA','RIZ'],'TO','👃','La nariz respira.'],['ojo','OJO',['O','JO'],'ME','👁️','El ojo observa.'],['brazo','BRAZO',['BRA','ZO'],'LI','💪','Muevo mi brazo.']],
  emociones:[['calma','CALMA',['CAL','MA'],'RI','🌿','Respiro con calma.'],['miedo','MIEDO',['MIE','DO'],'SA','😟','Puedo contar mi miedo.'],['risa','RISA',['RI','SA'],'PO','😄','Mi risa suena.'],['enojo','ENOJO',['E','NO','JO'],'LU','😠','El enojo puede pasar.'],['alegria','ALEGRÍA',['A','LE','GRÍ','A'],'TO','😊','Siento alegría.']],
  casa:[['mesa','MESA',['ME','SA'],'PO','🪑','La mesa está limpia.'],['cama','CAMA',['CA','MA'],'RI','🛏️','La cama es suave.'],['silla','SILLA',['SI','LLA'],'TU','🪑','Me siento en la silla.'],['taza','TAZA',['TA','ZA'],'ME','☕','La taza tiene agua.'],['casa','CASA',['CA','SA'],'LO','🏠','Esta es mi casa.']],
  escuela:[['lapiz','LÁPIZ',['LÁ','PIZ'],'TO','✏️','Uso el lápiz con calma.'],['libro','LIBRO',['LI','BRO'],'SA','📘','Abro mi libro.'],['clase','CLASE',['CLA','SE'],'MI','🏫','La clase empieza.'],['patio','PATIO',['PA','TIO'],'LU','🛝','Juego en el patio.'],['goma','GOMA',['GO','MA'],'RE','🧽','La goma borra.']],
  naturaleza:[['arbol','ÁRBOL',['ÁR','BOL'],'MI','🌳','El árbol tiene hojas.'],['nube','NUBE',['NU','BE'],'SA','☁️','La nube es blanca.'],['rio','RÍO',['RÍ','O'],'TA','🏞️','El río lleva agua.'],['hoja','HOJA',['HO','JA'],'PE','🍃','La hoja cae.'],['monte','MONTE',['MON','TE'],'LU','⛰️','El monte es alto.']],
  espacio:[['luna','LUNA',['LU','NA'],'RE','🌙','La luna brilla.'],['nave','NAVE',['NA','VE'],'TO','🚀','La nave despega.'],['marte','MARTE',['MAR','TE'],'LI','🔴','Marte se ve rojo.'],['cometa','COMETA',['CO','ME','TA'],'SA','☄️','El cometa cruza el cielo.'],['cielo','CIELO',['CIE','LO'],'PA','🌌','Miro el cielo.']],
  mar:[['peces','PECES',['PE','CES'],'TA','🐟','Los peces nadan.'],['ola','OLA',['O','LA'],'MI','🌊','La ola llega suave.'],['barco','BARCO',['BAR','CO'],'SE','⛵','El barco navega.'],['faro','FARO',['FA','RO'],'LU','🗼','El faro da luz.'],['pulpo','PULPO',['PUL','PO'],'NA','🐙','El pulpo tiene brazos.']],
  alimentos:[['manzana','MANZANA',['MAN','ZA','NA'],'PE','🍎','La manzana es roja.'],['pera','PERA',['PE','RA'],'TO','🍐','La pera es verde.'],['sopa','SOPA',['SO','PA'],'MI','🥣','La sopa está tibia.'],['queso','QUESO',['QUE','SO'],'LA','🧀','El queso es amarillo.'],['uva','UVA',['U','VA'],'RE','🍇','La uva es pequeña.']],
  transporte:[['auto','AUTO',['AU','TO'],'MI','🚗','El auto se detiene.'],['moto','MOTO',['MO','TO'],'SA','🏍️','La moto lleva casco.'],['bici','BICI',['BI','CI'],'RA','🚲','La bici tiene ruedas.'],['avion','AVIÓN',['A','VIÓN'],'PE','✈️','El avión vuela.'],['rueda','RUEDA',['RUE','DA'],'LO','🛞','La rueda gira.']],
  formas:[['rojo','ROJO',['RO','JO'],'MI','🔴','El círculo es rojo.'],['azul','AZUL',['A','ZUL'],'PE','🔵','El cielo es azul.'],['verde','VERDE',['VER','DE'],'TA','🟢','La hoja es verde.'],['circulo','CÍRCULO',['CÍR','CU','LO'],'SA','⭕','El círculo es redondo.'],['cuadrado','CUADRADO',['CUA','DRA','DO'],'MI','🟦','El cuadrado tiene lados.']],
  numeros:[['uno','UNO',['U','NO'],'TA','1️⃣','Veo un dinosaurio.'],['cuatro','CUATRO',['CUA','TRO'],'ME','4️⃣','Hay cuatro patas.'],['cinco','CINCO',['CIN','CO'],'LU','5️⃣','Tengo cinco dedos.'],['siete','SIETE',['SIE','TE'],'RA','7️⃣','Cuento hasta siete.'],['nueve','NUEVE',['NUE','VE'],'PO','9️⃣','El nueve va después del ocho.']],
  rutinas:[['dia','DÍA',['DÍ','A'],'NO','🌞','El día comienza.'],['noche','NOCHE',['NO','CHE'],'MI','🌙','La noche es tranquila.'],['bano','BAÑO',['BA','ÑO'],'LU','🛁','Voy al baño.'],['ropa','ROPA',['RO','PA'],'SE','👕','Preparo mi ropa.'],['sueno','SUEÑO',['SUE','ÑO'],'TA','😴','Tengo sueño.']],
  higiene:[['jabon','JABÓN',['JA','BÓN'],'MI','🧼','Uso jabón y agua.'],['dientes','DIENTES',['DIEN','TES'],'LU','🦷','Cepillo mis dientes.'],['agua','AGUA',['A','GUA'],'PE','💧','El agua limpia.'],['toalla','TOALLA',['TO','A','LLA'],'RI','🧻','Uso una toalla.'],['limpio','LIMPIO',['LIM','PIO'],'SA','✨','Quedo limpio.']],
  amistad:[['amigo','AMIGO',['A','MI','GO'],'PE','🧑‍🤝‍🧑','Saludo a mi amigo.'],['turno','TURNO',['TUR','NO'],'SA','🔄','Espero mi turno.'],['abrazo','ABRAZO',['A','BRA','ZO'],'MI','🤗','Puedo pedir un abrazo.'],['juego','JUEGO',['JUE','GO'],'TA','🎲','Compartimos el juego.'],['gracias','GRACIAS',['GRA','CIAS'],'LO','💛','Digo gracias.']],
  seguridad:[['clave','CLAVE',['CLA','VE'],'MI','🔑','La clave es privada.'],['adulto','ADULTO',['A','DUL','TO'],'PE','🧑','Pido ayuda a un adulto.'],['pausa','PAUSA',['PAU','SA'],'RI','⏸️','Hago una pausa.'],['aviso','AVISO',['A','VI','SO'],'LU','⚠️','Muestro el aviso.'],['privado','PRIVADO',['PRI','VA','DO'],'ME','🔒','Mis datos son privados.']]
};

for(const [topic,words] of Object.entries(extraWordSets)) miniWords.push(...words.map(([id,word,syllables,distractor,emoji,phrase])=>({id,topic,word,syllables,distractor,emoji,phrase})));

const extraStories=[
  ['tinkie-sonidos-bosque','animales','Tinkie escucha el bosque','🐾','GATO',['GA','TO'],['Tinkie visita un bosque lleno de sonidos suaves.','Escucha un miau y descubre un gato bajo un árbol.','Más adelante oye croar a una rana junto al río.','Un pato nada tranquilo y un perro mueve la cola.','Tinkie aprende a escuchar antes de nombrar cada animal.'],'¿Qué animal estaba bajo el árbol?',['Un gato','Un pato']],
  ['roki-descubre-cuerpo','cuerpo','Roki descubre su cuerpo','✋','MANO',['MA','NO'],['Roki levanta una mano para saludar a Tinkie.','Con sus ojos observa una mariposa de muchos colores.','Con la nariz respira el aroma de una flor.','Mueve los brazos y sonríe con toda la boca.','Roki agradece a su cuerpo todo lo que puede hacer.'],'¿Con qué parte observó la mariposa?',['Con los ojos','Con los pies']],
  ['tinkie-semáforo-emociones','emociones','El semáforo de las emociones','😊','CALMA',['CAL','MA'],['Tinkie siente alegría cuando comienza una nueva aventura.','Después escucha un ruido y nota un poco de miedo.','Se detiene, respira y encuentra nuevamente la calma.','Cuenta lo que siente y Roki escucha con atención.','Los amigos descubren que todas las emociones pueden nombrarse.'],'¿Qué hizo Tinkie para encontrar calma?',['Respiró','Corrió sin mirar']],
  ['roki-casa-ordenada','casa','Roki y la casa ordenada','🏠','CASA',['CA','SA'],['Roki llega a casa después de jugar en el jardín.','Deja su taza sobre la mesa y guarda cada juguete.','Coloca la silla en su lugar y prepara la cama.','Tinkie ayuda a revisar que el camino quede libre.','Ahora la casa está lista para descansar y jugar.'],'¿Dónde dejó Roki la taza?',['Sobre la mesa','Debajo de la cama']],
  ['tinkie-primer-dia-clase','escuela','Tinkie va a clase','✏️','LÁPIZ',['LÁ','PIZ'],['Tinkie prepara un lápiz, una goma y un libro.','Al entrar en clase saluda y busca su lugar.','Escucha una consigna corta y pregunta cuando tiene dudas.','Después juega con sus compañeros en el patio.','Tinkie vuelve contento porque aprendió paso a paso.'],'¿Qué llevó Tinkie para escribir?',['Un lápiz','Una cuchara']],
  ['roki-hoja-viajera','naturaleza','Roki y la hoja viajera','🍃','HOJA',['HO','JA'],['Una hoja cae de un árbol y aterriza junto a Roki.','El viento la lleva cerca de una nube reflejada en el río.','Roki sigue su viaje sin arrancar ninguna planta.','La hoja descansa finalmente al pie de un monte.','Roki aprende a observar la naturaleza con cuidado.'],'¿De dónde cayó la hoja?',['De un árbol','De una mesa']],
  ['tinkie-viaje-luna','espacio','Tinkie viaja a la Luna','🚀','LUNA',['LU','NA'],['Tinkie mira el cielo y prepara una nave imaginaria.','Despega despacio mientras un cometa cruza las estrellas.','Desde la ventana observa Marte como un punto rojo.','La nave llega a la Luna y aterriza con suavidad.','Tinkie regresa feliz con muchas preguntas nuevas.'],'¿Dónde aterrizó la nave?',['En la Luna','En el mar']],
  ['roki-faro-mar','mar','Roki y la luz del faro','🌊','FARO',['FA','RO'],['Roki camina por la playa y observa una ola pequeña.','A lo lejos, un barco sigue la luz de un faro.','Cerca de las rocas ve peces y un pulpo curioso.','Roki recoge un papel para mantener limpia la arena.','El mar queda tranquilo bajo la luz del faro.'],'¿Qué guiaba al barco?',['La luz del faro','Una pelota']],
  ['tinkie-merienda-colores','alimentos','La merienda de colores','🍎','MANZANA',['MAN','ZA','NA'],['Tinkie prepara una merienda con ayuda de un adulto.','Coloca una manzana, una pera y unas uvas.','También añade queso y espera que la sopa se enfríe.','Observa los colores y nombra cada alimento.','Después comparte la mesa y recoge su lugar.'],'¿Qué fruta era roja?',['La manzana','El queso']],
  ['roki-viaje-seguro','transporte','El viaje seguro de Roki','🚲','BICI',['BI','CI'],['Roki quiere recorrer el parque con su bici.','Antes de salir se pone el casco y revisa las ruedas.','Ve pasar un auto, una moto y un avión en el cielo.','Roki respeta el camino y se detiene cuando es necesario.','Termina el paseo tranquilo y guarda su bici.'],'¿Qué se puso Roki antes de salir?',['El casco','Una corona']],
  ['tinkie-formas-perdidas','formas','Las formas de colores','🟦','CÍRCULO',['CÍR','CU','LO'],['Tinkie encuentra un círculo rojo junto a una caja.','Dentro hay un cuadrado azul y una cinta verde.','Roki agrupa las figuras por forma y después por color.','Los amigos revisan juntos cada grupo sin correr.','Al terminar, todas las formas tienen su lugar.'],'¿Qué figura era roja?',['El círculo','El cuadrado']],
  ['roki-cuenta-huellas','numeros','Roki cuenta las huellas','🔢','CINCO',['CIN','CO'],['Roki encuentra una huella cerca de la cueva.','Después descubre cuatro huellas junto a un árbol.','Cuenta cinco, siete y finalmente nueve marcas pequeñas.','Tinkie señala cada huella para no contarla dos veces.','Los amigos comprueban el resultado con mucha calma.'],'¿Qué hicieron para no repetir una huella?',['La señalaron','Cerraron los ojos']],
  ['tinkie-rutina-tranquila','rutinas','El día tranquilo de Tinkie','🌞','DÍA',['DÍ','A'],['Tinkie despierta cuando comienza el día.','Va al baño, se viste y prepara su ropa.','Después juega, aprende y descansa cuando lo necesita.','Al llegar la noche guarda sus cosas con calma.','Tinkie siente sueño y se prepara para dormir.'],'¿Qué hizo Tinkie al llegar la noche?',['Guardó sus cosas','Comenzó otra carrera']],
  ['roki-burbujas-limpias','higiene','Roki y las burbujas limpias','🧼','JABÓN',['JA','BÓN'],['Roki vuelve del jardín con las manos llenas de tierra.','Abre el agua y usa un poco de jabón.','Frota con calma y después seca con la toalla.','También cepilla sus dientes con ayuda de un adulto.','Roki queda limpio y listo para merendar.'],'¿Qué utilizó Roki para lavar sus manos?',['Agua y jabón','Arena']],
  ['tinkie-juego-turnos','amistad','El juego de los turnos','🧑‍🤝‍🧑','TURNO',['TUR','NO'],['Tinkie y Roki encuentran un juego nuevo.','Los dos quieren comenzar, así que acuerdan esperar su turno.','Tinkie juega primero y después entrega la pieza a Roki.','Los amigos se ayudan y dicen gracias al terminar.','Compartir convierte el juego en una aventura mejor.'],'¿Qué esperaron los amigos?',['Su turno','La lluvia']],
  ['roki-aviso-extrano','seguridad','Roki pide ayuda digital','🔒','PRIVADO',['PRI','VA','DO'],['Roki ve un aviso extraño mientras juega acompañado.','El mensaje pide una clave y promete un premio enorme.','Roki no responde, hace una pausa y llama a un adulto.','Juntos cierran el aviso sin compartir información privada.','Roki aprende que pedir ayuda es una decisión valiente.'],'¿Qué hizo Roki con el aviso?',['Pidió ayuda a un adulto','Compartió su clave']]
];
for(const [id,topic,title,emoji,keyword,syllables,pages,text,options] of extraStories) miniStories.push({id,topic,title,emoji,keyword,syllables,pages,question:{text,options,correct:0}});

Object.assign(miniSoundLessons,{
  'animales-g':{letter:'G',model:'ggg, gato',correct:'GATO',choices:['GATO','PATO','OSO']},
  'cuerpo-b':{letter:'B',model:'bbb, boca',correct:'BOCA',choices:['BOCA','MANO','OJO']},
  'emociones-c':{letter:'C',model:'ccc, calma',correct:'CALMA',choices:['CALMA','RISA','MIEDO']},
  'casa-c':{letter:'C',model:'ccc, casa',correct:'CASA',choices:['CASA','MESA','TAZA']},
  'escuela-l':{letter:'L',model:'lll, lápiz',correct:'LÁPIZ',choices:['LÁPIZ','GOMA','PATIO']},
  'naturaleza-n':{letter:'N',model:'nnn, nube',correct:'NUBE',choices:['NUBE','HOJA','RÍO']},
  'espacio-l':{letter:'L',model:'lll, luna',correct:'LUNA',choices:['LUNA','NAVE','MARTE']},
  'mar-p':{letter:'P',model:'ppp, pulpo',correct:'PULPO',choices:['PULPO','BARCO','OLA']},
  'alimentos-m':{letter:'M',model:'mmm, manzana',correct:'MANZANA',choices:['MANZANA','PERA','UVA']},
  'transporte-b':{letter:'B',model:'bbb, bici',correct:'BICI',choices:['BICI','AUTO','MOTO']},
  'formas-r':{letter:'R',model:'rrr, rojo',correct:'ROJO',choices:['ROJO','AZUL','VERDE']},
  'numeros-c':{letter:'C',model:'ccc, cinco',correct:'CINCO',choices:['CINCO','UNO','NUEVE']},
  'rutinas-d':{letter:'D',model:'ddd, día',correct:'DÍA',choices:['DÍA','NOCHE','ROPA']},
  'higiene-j':{letter:'J',model:'jjj, jabón',correct:'JABÓN',choices:['JABÓN','AGUA','TOALLA']},
  'amistad-t':{letter:'T',model:'ttt, turno',correct:'TURNO',choices:['TURNO','AMIGO','JUEGO']},
  'seguridad-p':{letter:'P',model:'ppp, privado',correct:'PRIVADO',choices:['PRIVADO','CLAVE','AVISO']}
});

miniTopics.push(
  {id:'animales',group:'mundo',emoji:'🐾',title:'Animales cercanos',subtitle:'Escuchar, nombrar y clasificar',sound:'animales-g',story:'tinkie-sonidos-bosque',offline:'Imita un animal y di su nombre despacio.',objective:'Ampliar vocabulario y asociar sonidos con animales.',skill:'Discriminación auditiva y categorización.',observe:'Si reconoce el animal antes de leer la palabra.',wordIds:['gato','perro','pato','rana','oso']},
  {id:'cuerpo',group:'crecer',emoji:'✋',title:'Mi cuerpo',subtitle:'Partes, sentidos y movimiento',sound:'cuerpo-b',story:'roki-descubre-cuerpo',offline:'Toca una parte del cuerpo y nómbrala.',objective:'Reconocer y nombrar partes del cuerpo.',skill:'Esquema corporal y vocabulario funcional.',observe:'Si sigue una consigna corporal de un paso.',wordIds:['mano','boca','nariz','ojo','brazo']},
  {id:'emociones',group:'crecer',emoji:'😊',title:'Lo que siento',subtitle:'Calma, alegría, miedo y enojo',sound:'emociones-c',story:'tinkie-semáforo-emociones',offline:'Elige una cara y cuenta cómo se siente.',objective:'Identificar y expresar emociones básicas.',skill:'Conciencia emocional y lenguaje expresivo.',observe:'Si puede relacionar una emoción con una situación.',wordIds:['calma','miedo','risa','enojo','alegria']},
  {id:'casa',group:'aprender',emoji:'🏠',title:'Objetos de casa',subtitle:'Palabras de la vida diaria',sound:'casa-c',story:'roki-casa-ordenada',offline:'Busca dos objetos seguros y di dónde están.',objective:'Comprender vocabulario cotidiano y ubicación.',skill:'Denominación y comprensión espacial.',observe:'Si utiliza encima, debajo o dentro.',wordIds:['mesa','cama','silla','taza','casa']},
  {id:'escuela',group:'aprender',emoji:'🏫',title:'Vamos a la escuela',subtitle:'Materiales, lugares y rutinas',sound:'escuela-l',story:'tinkie-primer-dia-clase',offline:'Prepara lápiz y libro siguiendo dos pasos.',objective:'Anticipar y ordenar rutinas escolares.',skill:'Seguimiento de instrucciones y vocabulario escolar.',observe:'Si recuerda una consigna de dos elementos.',wordIds:['lapiz','libro','clase','patio','goma']},
  {id:'naturaleza',group:'mundo',emoji:'🌳',title:'Naturaleza',subtitle:'Árboles, nubes, ríos y montes',sound:'naturaleza-n',story:'roki-hoja-viajera',offline:'Observa una hoja y describe su color.',objective:'Observar y describir elementos naturales.',skill:'Atención visual y lenguaje descriptivo.',observe:'Si menciona al menos una característica.',wordIds:['arbol','nube','rio','hoja','monte']},
  {id:'espacio',group:'aventura',emoji:'🚀',title:'Viaje al espacio',subtitle:'Luna, naves, planetas y cometas',sound:'espacio-l',story:'tinkie-viaje-luna',offline:'Camina como astronauta y di LU · NA.',objective:'Motivar la lectura mediante curiosidad científica.',skill:'Conciencia silábica y secuenciación.',observe:'Si mantiene el orden de las sílabas.',wordIds:['luna','nave','marte','cometa','cielo']},
  {id:'mar',group:'mundo',emoji:'🌊',title:'El mundo del mar',subtitle:'Olas, peces, barcos y faros',sound:'mar-p',story:'roki-faro-mar',offline:'Mueve los brazos como una ola y di O · LA.',objective:'Relacionar vocabulario con un entorno.',skill:'Asociación semántica y coordinación motriz.',observe:'Si agrupa correctamente elementos del mar.',wordIds:['peces','ola','barco','faro','pulpo']},
  {id:'alimentos',group:'mundo',emoji:'🍎',title:'Alimentos y colores',subtitle:'Nombrar, comparar y elegir',sound:'alimentos-m',story:'tinkie-merienda-colores',offline:'Elige una fruta y describe su color.',objective:'Ampliar vocabulario de alimentación cotidiana.',skill:'Clasificación por color, forma y categoría.',observe:'Si diferencia fruta de otros alimentos.',wordIds:['manzana','pera','sopa','queso','uva']},
  {id:'transporte',group:'mundo',emoji:'🚲',title:'Transportes seguros',subtitle:'Ruedas, viajes y normas sencillas',sound:'transporte-b',story:'roki-viaje-seguro',offline:'Haz como si pedalearas y di BI · CI.',objective:'Reconocer transportes y hábitos de seguridad.',skill:'Vocabulario funcional y causa-efecto.',observe:'Si identifica una conducta segura.',wordIds:['auto','moto','bici','avion','rueda']},
  {id:'formas',group:'aprender',emoji:'🔵',title:'Colores y formas',subtitle:'Observar, comparar y agrupar',sound:'formas-r',story:'tinkie-formas-perdidas',offline:'Busca un objeto redondo y otro cuadrado.',objective:'Clasificar objetos por color y forma.',skill:'Percepción visual y conceptos básicos.',observe:'Si mantiene un criterio al clasificar.',wordIds:['rojo','azul','verde','circulo','cuadrado']},
  {id:'numeros',group:'aprender',emoji:'🔢',title:'Números y cantidades',subtitle:'Contar sin correr',sound:'numeros-c',story:'roki-cuenta-huellas',offline:'Cuenta cinco objetos tocando uno cada vez.',objective:'Relacionar conteo oral con cantidad.',skill:'Correspondencia uno a uno y atención sostenida.',observe:'Si evita repetir u omitir objetos.',wordIds:['uno','cuatro','cinco','siete','nueve']},
  {id:'rutinas',group:'crecer',emoji:'🌞',title:'Mi día paso a paso',subtitle:'Mañana, tarde y noche',sound:'rutinas-d',story:'tinkie-rutina-tranquila',offline:'Ordena tres acciones de su rutina diaria.',objective:'Comprender secuencias temporales cotidianas.',skill:'Planificación y memoria secuencial.',observe:'Si usa primero, después y al final.',wordIds:['dia','noche','bano','ropa','sueno']},
  {id:'higiene',group:'crecer',emoji:'🧼',title:'Autocuidado e higiene',subtitle:'Agua, jabón y dientes limpios',sound:'higiene-j',story:'roki-burbujas-limpias',offline:'Representa los pasos para lavar las manos.',objective:'Recordar rutinas básicas de autocuidado.',skill:'Secuenciación y autonomía.',observe:'Cuántos pasos recuerda sin ayuda.',wordIds:['jabon','dientes','agua','toalla','limpio']},
  {id:'amistad',group:'crecer',emoji:'🧑‍🤝‍🧑',title:'Amistad y turnos',subtitle:'Jugar, esperar y decir gracias',sound:'amistad-t',story:'tinkie-juego-turnos',offline:'Practica pedir y entregar un objeto por turnos.',objective:'Practicar habilidades sociales sencillas.',skill:'Espera, reciprocidad y lenguaje social.',observe:'Si tolera un turno breve con apoyo.',wordIds:['amigo','turno','abrazo','juego','gracias']},
  {id:'seguridad',group:'aprender',emoji:'🔒',title:'Seguridad digital',subtitle:'Pausa, privacidad y pedir ayuda',sound:'seguridad-p',story:'roki-aviso-extrano',offline:'Ensaya decir: paro y llamo a un adulto.',objective:'Reconocer cuándo detenerse y pedir ayuda.',skill:'Autoprotección y toma de decisiones.',observe:'Si identifica que una clave es privada.',wordIds:['clave','adulto','pausa','aviso','privado']}
);

const baseMeta={
  dinosaurios:['aventura','Reconocer sílabas directas mediante un interés motivador.','Conciencia silábica y vocabulario.','Si une las sílabas manteniendo el orden.'],
  aventuras:['aventura','Comprender rutas y secuencias sencillas.','Lenguaje espacial y planificación.','Si sigue una secuencia de dos pasos.'],
  heroes:['aventura','Relacionar el heroísmo con ayuda y cooperación.','Lenguaje social y comprensión.','Si identifica una acción amable.'],
  velocidad:['aventura','Practicar autocontrol dentro de una temática de velocidad.','Inhibición, pausa y secuenciación.','Si puede frenar y retomar una consigna.']
};
for(const topic of miniTopics.slice(0,4)){const [group,objective,skill,observe]=baseMeta[topic.id];Object.assign(topic,{group,objective,skill,observe});}

export const miniTopicGroups=[
  {id:'aventura',title:'Aventuras que motivan',emoji:'🚀'},
  {id:'mundo',title:'Descubro el mundo',emoji:'🌍'},
  {id:'crecer',title:'Aprendo sobre mí',emoji:'💛'},
  {id:'aprender',title:'Herramientas para aprender',emoji:'🧠'}
];
