import {store,todayCount} from '../core/store.js';
import {dailyMissions} from '../missions/mission-engine.js';
import {characterCard} from '../characters/characters.js';
import {puzzleMarkup, companion} from '../characters/companions.js';

const escapeHtml = value => String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));

export function homeScreen() {
  const state = store.get(), done = todayCount(state), goal = state.settings.dailyGoal || 3, missions = dailyMissions(goal);
  const mascotKey = state.profile.mascot || 'kiwi', mascot = companion(mascotKey);
  return `<section class="hero"><div class="hero-copy"><span class="hero-kicker">✨ Nueva aventura disponible</span><p class="eyebrow">Tu aventura, a tu ritmo</p><h1>Hola, <span>${escapeHtml(state.profile.name)}</span>.<br>${mascot.name} te acompaña.</h1><p>Misiones de lectura cortas, tranquilas y sin perder vidas.</p><div class="hero-actions"><a class="button" href="#jugar/${missions[Math.min(done,goal-1)].id}">Empezar misión <span aria-hidden="true">→</span></a><a class="button secondary" href="#misiones">🗺️ Ver el mapa</a></div></div><div class="hero-bubble" aria-hidden="true">${mascot.emoji}<br>¡Vamos juntos! <span>⭐</span></div></section>
  <section class="section daily-path"><div class="section-head"><div><p class="eyebrow">Plan de hoy</p><h2>${done>=goal?'¡Objetivo cumplido!':'Tu camino de '+goal+' pasos'}</h2></div><strong class="goal-count">${Math.min(done,goal)} <span>/ ${goal}</span></strong></div><div class="path-progress-wrap" style="--wolf-progress:${Math.min(100,done/goal*100)}"><div class="wolf-runner" role="img" aria-label="Lobito voxel corriendo por tu camino"><span class="wolf-tail"></span><span class="wolf-body"><i class="wolf-leg one"></i><i class="wolf-leg two"></i></span><span class="wolf-head"><i class="wolf-ear"></i><i class="wolf-eye"></i><i class="wolf-snout"></i></span></div><div class="progress"><span style="width:${Math.min(100,done/goal*100)}%"></span></div></div><div class="path-dots" aria-hidden="true">${Array.from({length:goal},(_,i)=>`<span class="${i<done?'done':''}">${i<done?'✓':i+1}</span>`).join('')}</div></section>
  <section class="section grid">${missions.map((mission,index)=>`<article class="card mission-card"><div class="mission-meta"><span class="pill">${mission.duration} min</span><span class="pill warm">${state.completed.includes(mission.id)?'✓ Hecha':'Paso '+(index+1)}</span></div><h3>${mission.title}</h3><p class="muted">Una misión breve con recompensa inmediata.</p><a class="button ${state.completed.includes(mission.id)?'secondary':''}" href="#jugar/${mission.id}">${state.completed.includes(mission.id)?'Repetir':'Jugar'}</a></article>`).join('')}</section>
  <section class="section companion-puzzle-grid"><article class="card accent"><p class="eyebrow">${mascot.name} dice</p>${characterCard(mascotKey)}</article>${puzzleMarkup(state, true)}</section>
  <section class="section card"><p class="eyebrow">Tu mochila</p><div class="stat-row"><div class="stat"><strong>${state.stars}</strong><span class="muted">estrellas</span></div><div class="stat"><strong>${state.xp}</strong><span class="muted">puntos</span></div><div class="stat"><strong>${state.completed.length}</strong><span class="muted">misiones</span></div></div></section>`;
}
